### ISSUE TITLE
Issue verifying QueryAsync<>

### ISSUE THREAD

**Issue by ghost** [laingsimon/Dapper.MoqTests#6]
The following exception is thrown

`System.MissingMethodException : Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.`

Usage:
`dbConnection.Verify(db => db.QueryAsync<Dto>(@"some sql", new { parameter1 = "foo" }));`

Full stack:
```
System.MissingMethodException : Method not found: 'System.Reflection.Emit.AssemblyBuilder System.AppDomain.DefineDynamicAssembly(System.Reflection.AssemblyName, System.Reflection.Emit.AssemblyBuilderAccess)'.
   at Dapper.MoqTests.ParametersObjectBuilder.AssemblyBuilder()
   at Dapper.MoqTests.ParametersObjectBuilder.ModuleBuilder()
   at Dapper.MoqTests.ParametersObjectBuilder.<>c.<.cctor>b__8_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Dapper.MoqTests.ParametersObjectBuilder.TypeBuilder()
   at Dapper.MoqTests.ParametersObjectBuilder.FromParameters(MockDbParameterCollection parameters)
   at Dapper.MoqTests.MockDbCommand.GetParameterLookup()
   at Dapper.MoqTests.MockDatabase.ExecuteReader(MockDbCommand command, Boolean isAsync)
   at Dapper.MoqTests.MockDbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 419
```

**Comment by laingsimon** [comment]
This has not been verified anywhere else, closing as as non-issue. It could be related to missing SDK/framework versions.
